#!/bin/bash

##########################
# SMP Script for CANDIDE #
##########################

# Receive email when job finishes or aborts
#PBS -M fabi.hervas@gmail.com
#PBS -m ea
# Set a name for the job
#PBS -N im4
#PBS -o /home/hervas/fhervas/workdir_skills/MultiBand_ImSim/scripts/log4
# Join output and errors in one file
#PBS -j oe
# Set maximum computing time (e.g. 5min)
#PBS -l walltime=20:00:00
# Request number of cores
#PBS -l nodes=1:ppn=48

# Full path to environment
#export SPENV="$HOME/.conda/envs/shapepipe"
#export SPDIR="$HOME/shapepipe"

# Activate conda environment
module load intelpython/3-2020.4
source activate wlenv
cd /home/hervas/fhervas/workdir_skills/MultiBand_ImSim/
# Run ShapePipe using full paths to executables
python modules/Run.py 3 -c scripts/config_UNIONS_to_im_swarp_4.ini  --sep_running_log
# Return exit code
exit 0
~                                                                                                                                                                                            
~                                                                                                                                                                                            
~                                                                                                                                                                                            
~                                                                                                                                                                                            
"candide_smp.sh" 31L, 695C                                                                                                                                                 31,1          All

