#!/bin/bash

##########################
# SMP Script for CANDIDE #
##########################

# Receive email when job finishes or aborts
# Set a name for the job
#SBATCH --job-name  small
#SBATCH --output /home/hervas/fhervas/workdir_skills/MultiBand_ImSim/scripts/small_${tag_run}
# Join output and errors in one file
# Set maximum computing time (e.g. 5min)
#SBATCH --time=20:00:00
# Request number of cores
#SBATCH --nodes=1 
#SBATCH --cpus-per-task=48
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks-per-core=1
#SBATCH --mem=0
#SBATCH --partition=comp,pscomp

# Full path to environment
#export SPENV="$HOME/.conda/envs/shapepipe"
#export SPDIR="$HOME/shapepipe"

# Activate conda environment
module load intelpython
source activate wlenv
cd /home/hervas/fhervas/workdir_skills/MultiBand_ImSim/
# Run ShapePipe using full paths to executables
export HDF5_USE_FILE_LOCKING="FALSE"
ulimit -u 65535

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
echo "index" $ind_run "tag" $tag_run  "seed" $seed "shear" $e1 $e2

srun python modules/Run.py 1 --runTag $tag_run --threads 12 --rng_seed $seed\
 --cosmic_shear $e1 $e2 -c scripts/config_UNIONS_to_im_$config.ini  --sep_running_log
exit 0
# Return exit code

~                                                                                                                                                                                            
~                                                                                                                                                                                            
~                                                                                                                                                                                            
~                                       
